template: failing-template.yml
terminationProtection: {{ var.terminationProtection }}
commandRole: arn:aws:iam::{{ var.ACCOUNT_1_ID }}:role/OrganizationAccountAccessRole
regions: eu-west-1
parameters:
  CreateWaitCondition: {{ var.create_wait_condition }}
