project: examples-cmd-resolver
commandRole: arn:aws:iam::{{ var.ACCOUNT_1_ID }}:role/OrganizationAccountAccessRole
regions: eu-west-1
parameters:
  CidrBlock:
    resolver: cmd
    command: echo 10.0.0.0/25
  ConfidentialParam:
    resolver: cmd
    command: echo hello
    confidential: true
  NonConfidentialParam:
    resolver: cmd
    command: echo world
    confidential: false
