regions: eu-west-1
template:
  inline: |
    Resources:
      LogGroup:
        Type: AWS::Logs::LogGroup
hooks:
  - name: test
    type: cmd
    stage: before
    operation: create
    command: ./install.sh
    cwd: app