#!/bin/bash

#
# Use this script to test locally built Takomo.
#
# You need to build the project before you can use this script.
#
# To build the project, go to the project root dir and run:
#
#   npm run build
#

node bin/tkm.mjs "$@"
