regions: us-east-1
template: stack3.yml
parameters:
  Code:
    resolver: external-stack-output
    stack: examples-external-parameter-resolver-account-a-stack1
    output: MyCode
    commandRole: arn:aws:iam::{{ var.ACCOUNT_1_ID }}:role/OrganizationAccountAccessRole
depends: /account-a/stack1.yml
