regions: eu-north-1
commandRole: arn:aws:iam::{{ var.ACCOUNT_1_ID }}:role/OrganizationAccountAccessRole
tags:
  first: this is string value
  second: 999
  third: true
  fourth: false
  fifth: 0
  sixth: "000001"
  seventh: "9"
schemas:
  tags: common-tags
template:
  inline: |
    Resources:
      LG:
        Type: AWS::Logs::LogGroup