schemas:
  parameters: MyParams
parameters:
  CostCenter: 1234
template:
  inline: |
    Parameters:
      CostCenter:
        Type: String
    Resources:
      Logs:
        Type: AWS::Logs::LogGroup