commandRole: arn:aws:iam::{{ var.ACCOUNT_1_ID }}:role/OrganizationAccountAccessRole
regions: eu-north-1
parameters:
  One:
    resolver: secret
    secretId: MyAccount1Secret1
  Two:
    resolver: secret
    region: eu-west-1
    secretId: MyAccount1Secret2
  Three:
    resolver: secret
    secretId: MyAccount1Secret4
    query: person.name
  Four:
    resolver: secret
    secretId: MyAccount2Secret1
    commandRole: arn:aws:iam::{{ var.ACCOUNT_2_ID }}:role/OrganizationAccountAccessRole
  Five:
    resolver: secret
    secretId: MyAccount1Secret3
    versionId: {{ var.updatedSecretVersionId }}
  Six:
    resolver: secret
    secretId: MyAccount1Secret3
    versionStage: AWSPREVIOUS
  Seven:
    resolver: secret
    secretId: MyAccount1Secret3
