commandRole: arn:aws:iam::{{ var.ACCOUNT_1_ID }}:role/OrganizationAccountAccessRole
regions: eu-west-1
parameters:
  One:
    resolver: ssm
    name: simple-param
  Two:
    resolver: ssm
    name: /param/with/path
  Three:
    resolver: ssm
    name: encrypted-param-name
  Four:
    resolver: ssm
    name: /param/in/other/region
    region: eu-north-1
  Five:
    resolver: ssm
    name: /param/with/role
    commandRole: arn:aws:iam::{{ var.ACCOUNT_1_ID }}:role/OrganizationAccountAccessRole