commandRole: arn:aws:iam::{{ var.ACCOUNT_1_ID }}:role/OrganizationAccountAccessRole
regions: eu-central-1
hooks:
  - name: hook1
    type: cmd
    command: aws sts get-caller-identity --output text --query Account
    exposeStackCredentials: {{ var.exposeStackCredentials }}
    exposeStackRegion: true
