masterAccountId: "{{ env.TKM_ORG_3_MASTER_ACCOUNT_ID }}"

organizationalUnits:
  Root/Master:
    accounts:
      - "{{ env.TKM_ORG_3_MASTER_ACCOUNT_ID }}"
  Root/One:
    configSets:
      - logs
    accounts:
      - "{{ env.TKM_ORG_3_ACCOUNT_01_ID }}"
  Root/Two:
    configSets:
      - other
      - logs
    accounts:
      - "{{ env.TKM_ORG_3_ACCOUNT_02_ID }}"
      - "{{ env.TKM_ORG_3_ACCOUNT_03_ID }}"
