Description: resolvers/external-stack-output/stack3
Parameters:
  Code:
    Type: String
    Description: Code
Resources:
  LogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub log-group-${Code}
