deploymentGroups:
  Example:
    targets:
      - name: one
        bootstrapRole: arn:aws:iam::{{ env.TKM_ORG_A_ACCOUNT_1_ID }}:role/OrganizationAccountAccessRole
        vars:
          accountId: "{{ env.TKM_ORG_A_ACCOUNT_1_ID }}"
      - name: two
        bootstrapRole: arn:aws:iam::{{ env.TKM_ORG_A_ACCOUNT_2_ID }}:role/OrganizationAccountAccessRole
        bootstrapConfigSets: logs2
        vars:
          accountId: "{{ env.TKM_ORG_A_ACCOUNT_2_ID }}"

configSets:
  logs2:
    description: Logging configs 2
    commandPaths:
      - /logs-2.yml
