deploymentGroups:
  GroupA/Child:
    configSets: example
    targets:
      - name: one
        deploymentRole: arn:aws:iam::{{ env.TKM_ORG_A_ACCOUNT_1_ID }}:role/OrganizationAccountAccessRole
      - name: two
        deploymentRole: arn:aws:iam::{{ env.TKM_ORG_A_ACCOUNT_2_ID }}:role/OrganizationAccountAccessRole

configSets:
  example:
    description: Example configs
    projectDir: others
    commandPaths:
      - /example.yml/eu-west-1
