deploymentGroups:
  Environments/Dev:
    configSets: logs
    targets:
      - name: one
        vars:
          accountId: "{{ var.ACCOUNT_1_ID }}"
      - name: two
        vars:
          accountId: "{{ var.ACCOUNT_2_ID }}"

  Environments/Test:
    configSets: logs
    targets:
      - name: three
        vars:
          accountId: "{{ var.ACCOUNT_3_ID }}"
      - name: four
        vars:
          accountId: "{{ var.ACCOUNT_4_ID }}"
      - name: five
        vars:
          accountId: "{{ var.ACCOUNT_5_ID }}"

configSets:
  logs:
    description: Logging configs
    commandPaths:
      - /logs.yml
