regions: us-east-1
parameters:
  Name: {{ var.name }}-us-east-1
template:
  inline: |
    Parameters:
      Name:
        Type: String
    Resources:
      Bucket:
        Type: AWS::S3::Bucket
        Properties:
          BucketName: !Ref Name
