regions: eu-west-1
template: t.yml
depends:
  - /e/eu-west-1/a-8.yml/eu-west-1
  - /e/eu-west-1/a-6.yml/eu-west-1
  - /e/eu-west-1/a-18.yml/eu-west-1
  - /e/eu-west-1/a-25.yml/eu-west-1
  - /e/eu-west-1/a-19.yml/eu-west-1
