deploymentGroups:
  One:
    deploymentRoleName: OrganizationAccountAccessRole
    targets:
      - name: one
        accountId: "{{ var.ACCOUNT_1_ID }}"
      - name: two
        accountId: "{{ var.ACCOUNT_2_ID }}"

  Two:
    targets:
      - name: three
        accountId: "{{ var.ACCOUNT_3_ID }}"
      - name: four
        accountId: "{{ var.ACCOUNT_4_ID }}"
      - name: five
        accountId: "{{ var.ACCOUNT_5_ID }}"