Description: resolvers/cmd/vpc
Parameters:
  CidrBlock:
    Type: String
    Description: VPC CIDR block
  ConfidentialParam:
    Type: String
    Description: Confidential parameter
  NonConfidentialParam:
    Type: String
    Description: Non-confidential parameter
  LastLine:
    Type: String
    Description: Last line of command output
Resources:
  VPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: !Ref CidrBlock
Outputs:
  ConfidentialParamValue:
    Value: !Ref ConfidentialParam
  NonConfidentialParamValue:
    Value: !Ref NonConfidentialParam
  LastLine:
    Value: !Ref LastLine
