Description: resolvers/stack-output/security-groups
Parameters:
  VpcId:
    Type: AWS::EC2::VPC::Id
    Description: VPC id
Resources:
  SecurityGroups:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Example security group
      VpcId: !Ref VpcId
