regions: eu-north-1
commandRole: arn:aws:iam::{{ var.accountId }}:role/OrganizationAccountAccessRole
tags:
  color: {{ var.color }}
  name: {{ var.nested.name }}
template:
  inline: |
    Resources:
      LogGroup:
        Type: AWS::Logs::LogGroup
    Outputs:
      DeploymentGroupName:
        Value: {{ target.deploymentGroup.name }}
      DeploymentGroupPath:
        Value: {{ target.deploymentGroup.path }}
      TargetName:
        Value: {{ target.name }}