commandRole: arn:aws:iam::{{ var.ACCOUNT_1_ID }}:role/OrganizationAccountAccessRole
regions: eu-west-1
parameters:
  CidrBlock:
    resolver: cmd
    command: echo 10.0.0.0/25
  ConfidentialParam:
    resolver: cmd
    command: echo hello
    confidential: true
    immutable: true
  NonConfidentialParam:
    resolver: cmd
    command: echo world
    confidential: false
    immutable: false
  LastLine:
    resolver: cmd
    command: cat sample.txt
    capture: last-line
