regions: eu-north-1
commandRole: arn:aws:iam::{{ var.ACCOUNT_1_ID }}:role/OrganizationAccountAccessRole
template: {{ var.templateVersion }}

{{> (lookup var 'paramsVersion') }}

{{> (lookup var 'tagsVersion') }}
